#!bin/bash
#стартираме програмата с Bash procA ab bc cd
#На стандартния вход се подава последователността от символи b c
#проследете какво ще изведе програмата

count=1
for i in 6 1 4 2
do 
   for each
   do if test $i -gt $#
         then count=` expr $count \* $i`
              echo $count $each >> f1
         else
         until false
	 do echo $*	
	 break 3
         done
      fi
   done
done
cat f1
read k1 k2
while cat f1 | grep $k1
do set $k1 $k2 $count
   shift
   echo $1 $2
   grep $2 f1 > f2
   wc -c f2
   exit
   echo END	 
done
wc -l f1
tail -2l f1
echo FIN
